var id = 100;
var fname = "Raj Deep";
var salary = 14000;
var result = true;
var msg = "Welcome to TypeScript";
msg = 100;
var eid = 110;
var ename = "Vikash Kale";
var esalary = 56000;
var accno;
accno = 112345;
console.log("id is " + id);
console.log("name is " + fname);
console.log("salary is " + salary);
console.log("result is " + result);
console.log("msg is " + msg);
console.log("eid " + eid);
console.log("ename " + ename);
console.log("esalary " + esalary);
console.log("accno " + accno);
